#logging.level.com，后面的路径指的是mybatis对应的方法接口所在的包。并不是mapper.xml所在的包。
server:
  max-http-header-size: 8192
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:5604086_dongruofan.xyz.pfx
    key-store-type: JKS
#    key-alias: tomcat_https
    key-password: wCRfK5vn
    key-store-password: wCRfK5vn

logging:
  level:
    com:
      site: debug
      site.blog.dao: debug
    root: info
spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    name: my-blog-datasource
#    url: jdbc:mysql://192.168.57.97:3306/manager?serverTimezone=GMT%2B8&useSSL=FALSE&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
    url: jdbc:mysql://114.55.92.162:3306/manager?serverTimezone=GMT%2B8&useSSL=FALSE&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 12345678
mybatis-plus:
  type-aliases-package: com.manager.system.entity
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      table-prefix: tb_
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用